spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DLRTM_HIBERNATE?serverTimezone=EST5EDT
    password: password
    username: dlrtm_hib
    #driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

